---
apiVersion: v1
kind: Service
metadata:
  name: tppg-service
spec:
  selector:
    app: tppg-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 31580
  type: NodePort
      